# Generated by Django 4.2.9 on 2024-03-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codeinfo',
            table='enum_code',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
